# -*- coding: utf-8 -*-
"""Analysis_Code_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-T-A0esHqR1qcIIDKQJAYmgzqxzjy0p
"""

from google.colab import files

# Upload your file manually
uploaded = files.upload()

import pandas as pd

# Load the dataset
df = pd.read_csv("/content/amazon_delivery_cleaned.csv")

# Check the first 5 rows to confirm it loaded correctly
print(df.head())

# 1. What is the average delivery speed by weather, traffic, vehicle, and area?

import pandas as pd

# Sample dataset
df = pd.DataFrame({
    "Weather Condition": ["Sunny", "Sunny", "Sunny", "Sunny",
                          "Cloudy", "Cloudy", "Cloudy", "Cloudy",
                          "Fog", "Fog", "Fog", "Fog",
                          "Sandstorms", "Sandstorms", "Sandstorms", "Sandstorms",
                          "Stormy", "Stormy", "Stormy", "Stormy",
                          "Windy", "Windy", "Windy", "Windy"],
    "Average Speed": [60, 55, 58, 62, 50, 48, 52, 49, 40, 42, 38, 41,
                      30, 35, 33, 31, 45, 47, 44, 46, 70, 72, 68, 75],
    "Category": ["A", "B", "C", "D"] * 6,
    "Traffic": ["Light", "Moderate", "Heavy", "Light"] * 6,
    "Vehicle Type": ["Car", "Truck", "Bike", "Car"] * 6,
    "Area": ["Urban", "Rural", "Industrial", "Urban"] * 6
})

# KPI 1: Average speed by weather
kpi_weather = df.groupby("Weather Condition")["Average Speed"].mean().sort_values(ascending=False)

# KPI 2: Average speed by category
kpi_category = df.groupby("Category")["Average Speed"].mean().sort_values(ascending=False)

# KPI 3: Average speed by traffic
kpi_traffic = df.groupby("Traffic")["Average Speed"].mean().sort_values(ascending=False)

# KPI 4: Average speed by vehicle type
kpi_vehicle = df.groupby("Vehicle Type")["Average Speed"].mean().sort_values(ascending=False)

# KPI 5: Average speed by area
kpi_area = df.groupby("Area")["Average Speed"].mean().sort_values(ascending=False)

# Display results
print(" KPI: Average Speed by Weather Condition")
print(kpi_weather)
print("\n KPI: Average Speed by Category")
print(kpi_category)
print("\n KPI: Average Speed by Traffic")
print(kpi_traffic)
print("\n KPI: Average Speed by Vehicle Type")
print(kpi_vehicle)
print("\n KPI: Average Speed by Area")
print(kpi_area)
plt.show()

# 2. Which area has longer delivery times?

# Compare delivery duration across different areas
area_times = df.groupby("Area")["Total_Delivery_Duration_minutes"].mean().sort_values()
print(area_times)

# Simple bar chart
import matplotlib.pyplot as plt
area_times.plot(kind="bar")
plt.ylabel("Average Delivery Duration (minutes)")
plt.title("Average Delivery Duration by Area")
plt.show()

# 3. Can we predict delivery time from distance and traffic?

import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

# --- Step 1: Encode Traffic into dummy variables ---
df_encoded = pd.get_dummies(df[['Delivery_Distance_km', 'Traffic']], drop_first=True)

# --- Step 2: Define features (X) and target (y) ---
X = df_encoded.astype(float)
y = pd.to_numeric(df['Total_Delivery_Duration_minutes'], errors='coerce')

# Drop missing values
X = X.loc[y.notna()]
y = y.loc[y.notna()]

# --- Step 3: Add constant for intercept ---
X = sm.add_constant(X)

# --- Step 4: Fit OLS regression model ---
model = sm.OLS(y, X).fit()

# --- Step 5: Show summary results ---
print(model.summary())

# --- Step 6: Actual vs Predicted plot ---
y_pred = model.predict(X)

plt.figure(figsize=(8,6))
plt.scatter(y, y_pred, alpha=0.3)
plt.xlabel("Actual Delivery Time (minutes)")
plt.ylabel("Predicted Delivery Time (minutes)")
plt.title("Actual vs Predicted Delivery Time")
plt.plot([y.min(), y.max()], [y.min(), y.max()], color="red", linestyle="--")
plt.show()

# --- Step 7: Visualize coefficients ---
coef = model.params.sort_values()
coef.plot(kind="barh", figsize=(8,6))
plt.title("Regression Coefficients (Effect on Delivery Time)")
plt.xlabel("Effect (minutes)")
plt.show()

# 4. Which vehicle is fastest in heavy traffic?

import pandas as pd
import matplotlib.pyplot as plt

# Clean Traffic column (lowercase + strip spaces)
df["Traffic"] = df["Traffic"].str.strip().str.lower()

# Filter dataset for high traffic only
heavy_traffic = df[df["Traffic"] == "high"]

if heavy_traffic.empty:
    print("Still no rows found with Traffic = 'high'")
else:
    # Calculate the average speed per vehicle
    vehicle_speed = heavy_traffic.groupby("Vehicle")["Speed_kmph"].mean().sort_values(ascending=False)

    # Get fastest vehicle
    fastest_vehicle = vehicle_speed.idxmax()
    fastest_speed = vehicle_speed.max()
    print(f"Fastest vehicle in heavy traffic: {fastest_vehicle} ({fastest_speed:.2f} km/h)")

    # Highlight fastest vehicle in a different color
    colors = ["skyblue" if v != fastest_vehicle else "orange" for v in vehicle_speed.index]

    # Plot results
    vehicle_speed.plot(kind="bar", color=colors)
    plt.ylabel("Average Speed (km/h)")
    plt.title("Average Vehicle Speed under Heavy Traffic")
    plt.show()

# 5. Do younger or older agents deliver faster?

import pandas as pd
import matplotlib.pyplot as plt

# Calculate the average delivery speed for each age segment
age_speed = (
    df.groupby("Age_Segment")["Speed_kmph"]
    .mean()
    .dropna()
    .sort_values(ascending=False)
)

if age_speed.empty:
    print("No data found for Age_Segment.")
else:
    # Print results
    print("Average speed by age segment:")
    print(age_speed)

    # Fastest age segment
    fastest_age = age_speed.idxmax()
    fastest_speed = age_speed.max()
    print(f"Fastest segment: {fastest_age} ({fastest_speed:.2f} km/h)")

    # Highlight fastest segment in orange
    colors = ["skyblue" if seg != fastest_age else "orange" for seg in age_speed.index]

    # Plot the results
    age_speed.plot(kind="bar", color=colors)
    plt.ylabel("Average Speed (km/h)")
    plt.title("Delivery Speed by Age Segment")
    plt.show()